import{r as e}from"./assets/rolldown-runtime-Cq0jCQ29.js";import"./assets/styles-BRfZMDc1.js";import{n as t,t as n}from"./assets/vendor-D789xMJy.js";var r=e(t(),1);function i(e,t=`success`){let n={message:e,position:`topRight`,background:`#ef4040`,timeout:5e3};switch(t){case`success`:r.default.success(n);break;case`error`:r.default.error(n);break;case`warning`:r.default.warning(n);break;case`info`:r.default.info(n);break;case`default`:r.default.error({message:`Invalid type of toast: ${t}`,position:`topRight`,timeout:5e3});break}}var a=`https://dummyjson.com`,o={CATEGORIES:`/products/category-list`,PRODUCTS:`/products`,BYCATEGORY:`/products/category/`};n.defaults.baseURL=a;async function s(){let{data:e}=await n(`${o.CATEGORIES}`);return e}async function c(e){let t=(e-1)*12,{data:r}=await n(`${o.PRODUCTS}?limit=12&skip=${t}`);return r}async function l(e,t){let r=(t-1)*12,{data:i}=await n(`${o.BYCATEGORY}${e}?limit=12&skip=${r}`);return i}var u={categories:document.querySelector(`.categories`),products:document.querySelector(`.products`),loadMoreBtn:document.querySelector(`.load-more-btn`),loader:document.querySelector(`.loader`),notFound:document.querySelector(`.not-found`)};function d(e){let t=e.map(e=>`<li class="categories__item">
   <button class="categories__btn" type="button" data-category="${e}">${e}</button>
 </li>`).join(``);u.categories.innerHTML=t}function f(e){let t=e.map(({thumbnail:e,title:t,id:n,brand:r,category:i,price:a})=>`<li class="products__item" data-id="${n}">
    <img class="products__image" src="${e}" alt="${t}"/>
    <p class="products__title">${t}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${r}</span></p>
    <p class="products__category">Category: ${i}</p>
    <p class="products__price">Price: ${a}$</p>
 </li>`).join(``);u.products.insertAdjacentHTML(`beforeend`,t)}function p(){u.loadMoreBtn.classList.remove(`is-hidden`)}function m(){u.loadMoreBtn.classList.add(`is-hidden`)}function h(){u.loader.classList.remove(`is-hidden`)}function g(){u.loader.classList.add(`is-hidden`)}function _(){u.notFound.classList.add(`not-found--visible`)}function v(){u.notFound.classList.remove(`not-found--visible`)}function y(){u.products.innerHTML=``}var b=1,x=``;async function S(){try{b=1,v(),m(),h(),d([`all`,...await s()]),document.querySelector(`.categories__btn`).classList.add(`categories__btn--active`);let{products:e,skip:t,total:n}=await c(b);if(e.length===0){_();return}f(e),n-(t+12)>0&&p()}catch{i(`Something went wrong, try again, please`,`error`)}finally{g()}}async function C(){b+=1;try{if(v(),m(),h(),x===``){let{products:e,skip:t,total:n}=await c(b);if(e.length===0){_();return}f(e),n-(t+12)>0&&p()}else{let{products:e,skip:t,total:n}=await l(x,b);if(e.length===0){_();return}f(e),n-(t+12)>0&&p()}}catch{i(`Something went wrong, try again, please`,`error`)}finally{g()}}async function w(e){if(e.target.nodeName===`BUTTON`){x=e.target.dataset.category,document.querySelectorAll(`.categories__btn`).forEach(e=>e.classList.remove(`categories__btn--active`)),e.target.classList.add(`categories__btn--active`);try{if(b=1,v(),m(),h(),y(),x===`all`){let{products:e,skip:t,total:n}=await c(b);if(e.length===0){_();return}f(e),n-(t+12)>0&&p()}else{let{products:e,skip:t,total:n}=await l(x,b);if(e.length===0){_();return}f(e),n-(t+12)>0&&p()}}catch{i(`Something went wrong, try again, please`,`error`)}finally{g()}}}document.addEventListener(`DOMContentLoaded`,S),u.loadMoreBtn.addEventListener(`click`,C),u.categories.addEventListener(`click`,w);
//# sourceMappingURL=index.js.map