export const refs = {
  categories: document.querySelector('.categories'),
  products: document.querySelector('.products'),
  loadMoreBtn: document.querySelector('.load-more-btn'),
  loader: document.querySelector('.loader'),
  notFound: document.querySelector('.not-found'),
  modal: document.querySelector('.modal'),
  modalCloseBtn: document.querySelector('.modal__close-btn'),
  modalProduct: document.querySelector('.modal-product'),
  body: document.body,
  searchForm: document.querySelector('.search-form'),
  searchInput: document.querySelector('.search-form__input'),
  clearBtn: document.querySelector('.search-form__btn-clear'),
  navCountSpan: document.querySelector('.nav__count'),
  modalProductBtnCart: document.querySelector('.modal-product__btn--cart'),
};
